### PR TITLE
[Fixes #121, Fixes #120] Make data protection follow the options model

### LINKED ISSUE #120: Make Microsoft.AspNetCore.DataProtection.DataProtectionProvider class static
https://github.com/aspnet/DataProtection/blob/dev/src/Microsoft.AspNetCore.DataProtection.Extensions/DataProtectionProvider.cs

https://docs.asp.net/en/latest/security/data-protection/configuration/non-di-scenarios.html

This class is meant to be used in Non-DI scenarios as an entry point for creating a IDataProtectionProvider instance that can be used acrross the app to protect and unprotect data. As such, making it static will avoid any confusion of mixing it with DI enabled scenarios. The advantages are:

* Clearly separates DI scenarios from non DI scenarios. (You can't register a static class in a DI Container)
* Makes the class cleaner (The current implementation creates a whole data protection stack inside the constructor, and wraps the default implementation without any perceived benefit.
* Is arguably less discoverable, it's easier to 'dot' into a static class and see a method that you can use to construct an instance of the thing that you want, than having to use 'new' on the type.
* By doing all the setup in a constructor, we are cornering ourselves in the future if we wan't to do more complicated things inside the setup, like for example, caching existing DataProtectionProviders.

As a reference, here is the implementation as a static class
```c#
using System;
using System.IO;
using Microsoft.Extensions.DependencyInjection;

namespace Microsoft.AspNetCore.DataProtection
{
    public static class DataProtectionProvider
    {
        public static IDataProtectionProvider Create(DirectoryInfo keyDirectory)
        {
            return Create(keyDirectory, setupAction: null);
        }

        public static IDataProtectionProvider Create(
            DirectoryInfo keyDirectory,
            Action<DataProtectionConfiguration> setupAction)
        {
            if (keyDirectory == null)
            {
                throw new ArgumentNullException(nameof(keyDirectory));
            }

            var serviceCollection = new ServiceCollection();
            var builder = serviceCollection.AddDataProtection();
            builder.PersistKeysToFileSystem(keyDirectory);

            if(setupAction != null)
            {
                setupAction(builder);
            }

            return serviceCollection.BuildServiceProvider().GetRequiredService<IDataProtectionProvider>();
        }
    }
}
```

### LINKED ISSUE #121: Make DataProtection follow the Options model
This repo requires some cleanup to adapt it to the pattern we follow on other parts of the framework

### PR DESCRIPTION
**Pull request by javiercn**

### CODE REVIEW

**Comment by javiercn** [comment]
Things to pay attention to:
* Comments (There's been a lot of copy paste, so mistakes can happen).
* Method names
* Null checks for arguments
* Overload with configuration action calls parameterless overload.
* Parameterless overload does the work and brings in direct depenendencies
  (Like routing on MVC, for most repositories it means making sure AddOptions is called).

**Comment by HaoK** [comment]
Don't introduce IDataProtectionBuilder here either

**Comment by Eilon** [comment]
@HaoK what's the concern here? This seems to follow the interface-builder pattern we have elsewhere, no? Is the concern with this specific change, or with changing it at all?

**Comment by HaoK** [comment]
The interface/builder pattern was only in MVC, and not anywhere else (not here/EF/or identity).  The interface pattern seems more suited for MVC which has tons of assemblies layering on methods, and just an extra interface everywhere else...

@divega and I pushed back on identity for that reason, and I was just echoing that comment here when I saw a builder interface added.

**Comment by davidfowl** [comment]
It would be good to look at some samples of this being called before going further.

**Comment by javiercn** [comment]
@davidfowl 

```
services
  .AddDataProtection(options =>{...})
  .PersistXXX()
  .UseFileXXX()
```

**Comment by javiercn** [comment]
@blowdart

**Comment by blowdart** [comment]
Data Protection isn't just for MVC. If the builder is an MVC only thing then it needs to go. 

How does it cope with options that are mutually exclusive? Or if you try to set the same thing twice?

**Comment by Eilon** [comment]
Builders aren't an MVC thing. I'm setting up a meeting for Thursday to discuss this pattern in general.

**Comment by javiercn** [comment]
@Eilon @rynowak I believe I've incorporated all the changes we discussed on the meeting

**Comment by javiercn** [comment]
@Eilon ping? 😀

File: src/Microsoft.AspNetCore.DataProtection.Extensions/DataProtectionProvider.cs [hunk 1]
```diff
@@ -8,21 +8,19 @@
 namespace Microsoft.AspNetCore.DataProtection
 {
     /// <summary>
-    /// A simple implementation of an <see cref="IDataProtectionProvider"/> where keys are stored
-    /// at a particular location on the file system.
+    /// An entry point class for creating an <see cref="IDataProtectionProvider"/> where keys are stored
+    /// at a particular location on the file system on non dependency injection enabled scenarios.
```
Comment (Eilon) [inline src/Microsoft.AspNetCore.DataProtection.Extensions/DataProtectionProvider.cs]: I'd put the `on non dependency injection enabled scenarios` part in a `<remarks>` section. Also, the phrasing is a bit nerdy. Perhaps something like `<remarks>Use this method when not using dependency injection to provide the service to the application.</remarks>`?

File: src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs [hunk 2]
```diff
@@ -17,196 +17,195 @@
...
+    public static class DataProtectionBuilderExtensions
     {
         /// <summary>
-        /// Creates a new configuration object linked to a <see cref="IServiceCollection"/>.
+        /// Sets the unique name of this application within the data protection system.
         /// </summary>
-        public DataProtectionConfiguration(IServiceCollection services)
+        /// <param name="builder">The <see cref="IDataProtectionBuilder"/>.</param>
+        /// <param name="applicationName">The application name.</param>
+        /// <returns>The 'this' instance.</returns>
```
Comment (Eilon) [inline src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs]: Yuck. Copy what we do elsewhere. I hope we don't do this anywhere else.

File: src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs [hunk 3]
```diff
@@ -424,61 +474,73 @@ public DataProtectionConfiguration UseCustomCryptographicAlgorithms(CngGcmAuthen
...
                 }
             }
         }
 
-        private void Use(ServiceDescriptor descriptor)
+        private static void Use(IServiceCollection services, ServiceDescriptor descriptor)
         {
-            RemoveAllServicesOfType(descriptor.ServiceType);
-            Services.Add(descriptor);
+            RemoveAllServicesOfType(services, descriptor.ServiceType);
```
Comment (Eilon) [inline src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs]: In the meeting didn't we say something about this method? Like why does it exist? Is it needed?

File: src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs (hunk 2 above)
Comment (Eilon) [inline src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs]: Looks like elsewhere in this repo we do the more correct "returns a reference to this instance after the operation completed" or whatever - so let's use that everywhere here.

**Comment by Eilon** [comment]
Sorry for the delay. Looks like it's 99% :shipit: , just a few things.

File: src/Microsoft.AspNetCore.DataProtection.Extensions/DataProtectionProvider.cs (hunk 1 above)
Comment (rynowak) [inline src/Microsoft.AspNetCore.DataProtection.Extensions/DataProtectionProvider.cs]: > An entry point class for creating an <see cref="IDataProtectionProvider"/> where keys are stored at a particular location on the file system on non dependency injection enabled scenarios.

Suggest:

> Contains factory methods for creating an <see cref="IDataProtectionProvider"/> where keys are stored at a particular location in the file system for non-dependency-injection scenarios.

File: src/Microsoft.AspNetCore.DataProtection.Extensions/DataProtectionProvider.cs [hunk 4]
```diff
@@ -31,9 +29,11 @@ public DataProtectionProvider(DirectoryInfo keyDirectory)
...
         /// <param name="keyDirectory">The <see cref="DirectoryInfo"/> in which keys should be stored. This may
         /// represent a directory on a local disk or a UNC share.</param>
-        /// <param name="configure">An optional callback which provides further configuration of the data protection
-        /// system. See <see cref="DataProtectionConfiguration"/> for more information.</param>
-        public DataProtectionProvider(DirectoryInfo keyDirectory, Action<DataProtectionConfiguration> configure)
+        /// <param name="setupAction">An optional callback which provides further configuration of the data protection
+        /// system. See <see cref="IDataProtectionBuilder"/> for more information.</param>
+        public static IDataProtectionProvider Create(
+            DirectoryInfo keyDirectory,
+            Action<IDataProtectionBuilder> setupAction)
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.DataProtection.Extensions/DataProtectionProvider.cs]: Didn't you do a pass to make these callbacks non-optional in a bunch of places? :trollface:

File: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/AuthenticatedEncryptorDescriptor.cs [hunk 5]
```diff
@@ -8,22 +8,22 @@ namespace Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.Configurat
...
     /// A descriptor which can create an authenticated encryption system based upon the
-    /// configuration provided by an <see cref="AuthenticatedEncryptionOptions"/> object.
+    /// configuration provided by an <see cref="AuthenticatedEncryptionSettings"/> object.
     /// </summary>
     public sealed class AuthenticatedEncryptorDescriptor : IAuthenticatedEncryptorDescriptor
     {
         private readonly IServiceProvider _services;
 
-        public AuthenticatedEncryptorDescriptor(AuthenticatedEncryptionOptions options, ISecret masterKey)
+        public AuthenticatedEncryptorDescriptor(AuthenticatedEncryptionSettings options, ISecret masterKey)
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/AuthenticatedEncryptorDescriptor.cs]: options -> settings

File: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/CngCbcAuthenticatedEncryptorConfiguration.cs [hunk 6]
```diff
@@ -13,23 +13,23 @@ public sealed class CngCbcAuthenticatedEncryptorConfiguration : IAuthenticatedEn
     {
         private readonly IServiceProvider _services;
 
-        public CngCbcAuthenticatedEncryptorConfiguration(CngCbcAuthenticatedEncryptionOptions options)
+        public CngCbcAuthenticatedEncryptorConfiguration(CngCbcAuthenticatedEncryptionSettings options)
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/CngCbcAuthenticatedEncryptorConfiguration.cs]: options -> settings

File: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/CngCbcAuthenticatedEncryptorDescriptor.cs [hunk 7]
```diff
@@ -9,22 +9,22 @@ namespace Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.Configurat
...
     /// A descriptor which can create an authenticated encryption system based upon the
-    /// configuration provided by an <see cref="CngCbcAuthenticatedEncryptionOptions"/> object.
+    /// configuration provided by an <see cref="CngCbcAuthenticatedEncryptionSettings"/> object.
     /// </summary>
     public sealed class CngCbcAuthenticatedEncryptorDescriptor : IAuthenticatedEncryptorDescriptor
     {
         private readonly ILogger _log;
 
-        public CngCbcAuthenticatedEncryptorDescriptor(CngCbcAuthenticatedEncryptionOptions options, ISecret masterKey)
+        public CngCbcAuthenticatedEncryptorDescriptor(CngCbcAuthenticatedEncryptionSettings options, ISecret masterKey)
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/CngCbcAuthenticatedEncryptorDescriptor.cs]: options -> settings

File: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/CngGcmAuthenticatedEncryptorConfiguration.cs [hunk 8]
```diff
@@ -13,23 +13,23 @@ public sealed class CngGcmAuthenticatedEncryptorConfiguration : IAuthenticatedEn
     {
         private readonly IServiceProvider _services;
 
-        public CngGcmAuthenticatedEncryptorConfiguration(CngGcmAuthenticatedEncryptionOptions options)
+        public CngGcmAuthenticatedEncryptorConfiguration(CngGcmAuthenticatedEncryptionSettings options)
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/CngGcmAuthenticatedEncryptorConfiguration.cs]: Noticing a pattern here

File: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/CngGcmAuthenticatedEncryptorDescriptor.cs [hunk 9]
```diff
@@ -9,22 +9,22 @@ namespace Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.Configurat
...
     /// A descriptor which can create an authenticated encryption system based upon the
-    /// configuration provided by an <see cref="CngGcmAuthenticatedEncryptionOptions"/> object.
+    /// configuration provided by an <see cref="CngGcmAuthenticatedEncryptionSettings"/> object.
     /// </summary>
     public sealed class CngGcmAuthenticatedEncryptorDescriptor : IAuthenticatedEncryptorDescriptor
     {
         private readonly ILogger _log;
 
-        public CngGcmAuthenticatedEncryptorDescriptor(CngGcmAuthenticatedEncryptionOptions options, ISecret masterKey)
+        public CngGcmAuthenticatedEncryptorDescriptor(CngGcmAuthenticatedEncryptionSettings options, ISecret masterKey)
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/CngGcmAuthenticatedEncryptorDescriptor.cs]: :sleeping:

File: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/ManagedAuthenticatedEncryptorConfiguration.cs [hunk 10]
```diff
@@ -14,23 +14,23 @@ public sealed class ManagedAuthenticatedEncryptorConfiguration : IAuthenticatedE
     {
         private readonly IServiceProvider _services;
 
-        public ManagedAuthenticatedEncryptorConfiguration(ManagedAuthenticatedEncryptionOptions options)
+        public ManagedAuthenticatedEncryptorConfiguration(ManagedAuthenticatedEncryptionSettings options)
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/ManagedAuthenticatedEncryptorConfiguration.cs]: OK, officially not commenting on this one.

File: src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/ManagedAuthenticatedEncryptorDescriptorDeserializer.cs [hunk 11]
```diff
@@ -42,7 +42,7 @@ public IAuthenticatedEncryptorDescriptor ImportFromXml(XElement element)
             //   <masterKey>...</masterKey>
             // </descriptor>
 
-            var options = new ManagedAuthenticatedEncryptionOptions();
+            var options = new ManagedAuthenticatedEncryptionSettings();
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.DataProtection/AuthenticatedEncryption/ConfigurationModel/ManagedAuthenticatedEncryptorDescriptorDeserializer.cs]: this one is different though

File: src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs [hunk 12]
```diff
@@ -17,196 +17,195 @@
...
 namespace Microsoft.AspNetCore.DataProtection
 {
-#if !NETSTANDARD1_3
     /// <summary>
-    /// Provides access to configuration for the data protection system, which allows the
-    /// developer to configure default cryptographic algorithms, key storage locations,
-    /// and the mechanism by which keys are protected at rest.
+    /// Extensions for configuring data protection using an <see cref="IDataProtectionBuilder"/>.
     /// </summary>
-    /// <remarks>
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs]: Why delete all this stuff?

File: src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs (hunk 2 above)
Comment (rynowak) [inline src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs]: This would usually say something like `A reference to the <see cref="IDataProtectionBuilder" /> after this operation has completed.`

File: src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs [hunk 13]
```diff
@@ -424,61 +474,73 @@ public DataProtectionConfiguration UseCustomCryptographicAlgorithms(CngGcmAuthen
...
+                throw new ArgumentNullException(nameof(builder));
+            }
+
+            Use(builder.Services, DataProtectionServiceDescriptors.IDataProtectionProvider_Ephemeral());
+            return builder;
         }
 
         /*
          * UTILITY ISERVICECOLLECTION METHODS
          */
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs]: This makes me a sad panda :panda_face:

File: src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs [hunk 14]
```diff
@@ -17,196 +17,195 @@
...
         /// <summary>
-        /// Configures miscellaneous global options.
+        /// Configures the key management options for the data protection system.
         /// </summary>
-        /// <param name="setupAction">A callback that configures the global options.</param>
+        /// <param name="builder">The <see cref="IDataProtectionBuilder"/>.</param>
+        /// <param name="setupAction">An <see cref="Action{KeyManagementOptions}"/> to configure the provided<see cref="KeyManagementOptions"/>.</param>
         /// <returns>The 'this' instance.</returns>
-        public DataProtectionConfiguration ConfigureGlobalOptions(Action<DataProtectionOptions> setupAction)
+        public static IDataProtectionBuilder AddKeyManagement(this IDataProtectionBuilder builder, Action<KeyManagementOptions> setupAction)
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs]: This should be `AddKeyManagementOptions`

File: src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs [hunk 15]
```diff
@@ -17,196 +17,195 @@
...
-            if (services == null)
+            if (builder == null)
             {
-                throw new ArgumentNullException(nameof(services));
+                throw new ArgumentNullException(nameof(builder));
             }
 
-            Services = services;
-        }
+            builder.Services.Configure<DataProtectionOptions>(options =>
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs]: There should also be an `AddDataProtectionOptions` somewhere in here

File: src/Microsoft.AspNetCore.DataProtection/DataProtectionServiceDescriptors.cs [hunk 16]
```diff
@@ -58,13 +58,13 @@ public static ServiceDescriptor ConfigureOptions_DefaultKeyLifetime(int numDays)
         /// </summary>
         public static ServiceDescriptor IAuthenticatedEncryptorConfiguration_Default()
         {
-            return IAuthenticatedEncryptorConfiguration_FromOptions(new AuthenticatedEncryptionOptions());
+            return IAuthenticatedEncryptorConfiguration_FromOptions(new AuthenticatedEncryptionSettings());
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.DataProtection/DataProtectionServiceDescriptors.cs]: From settings?

File: src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs (hunk 12 above)
Comment (Eilon) [inline src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs]: It's not deleted, it moved verbatim to the builder interface file.

Comment (rynowak) [inline src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs]: :+1: - I don't read things, I just go with my gut.

Comment (Eilon) [inline src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs]: Don't worry, it caught me out too the first time I saw the code :smile:

File: src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs (hunk 3 above)
Comment (javiercn) [inline src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs]: Yes, but it doesn't affect public API and I'm trying not to change behavior. We know it works and we can fix it later if we want, given that it's private and just 10 lines of code, I don't feel it's worth fixing at this point.

File: src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs (hunk 15 above)
Comment (javiercn) [inline src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs]: It was called ConfigureGlobalOptions and we decided to get rid of it.

File: src/Microsoft.AspNetCore.DataProtection.Extensions/DataProtectionProvider.cs (hunk 4 above)
Comment (javiercn) [inline src/Microsoft.AspNetCore.DataProtection.Extensions/DataProtectionProvider.cs]: Thisi s addressed

File: src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs [hunk 17]
```diff
@@ -0,0 +1,546 @@
...
+            return builder;
+        }
+
+        /// <summary>
+        /// Configures the key management options for the data protection system.
+        /// </summary>
+        /// <param name="builder">The <see cref="IDataProtectionBuilder"/>.</param>
+        /// <param name="setupAction">An <see cref="Action{KeyManagementOptions}"/> to configure the provided<see cref="KeyManagementOptions"/>.</param>
+        /// <returns>A reference to the <see cref="IDataProtectionBuilder" /> after this operation has completed.</returns>
+        public static IDataProtectionBuilder AddKeyManagement(this IDataProtectionBuilder builder, Action<KeyManagementOptions> setupAction)
```
Comment (rynowak) [inline src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs]: `AddKeyManagementOptions`

**Comment by rynowak** [comment]
:shipit:
