### PR TITLE
Make ILoggerFactory an optional service on any DI-injected services

### LINKED ISSUE #243: Calling AddDataProtection before AddLogging pollutes service collection with NullLoggerFactory
Order shouldn't matter. The call to AddLogging should win.

This was broken by https://github.com/aspnet/DataProtection/issues/134.

```c#
    public class Program
    {
        public static void Main(string[] args)
        {
            // Call AddDataProtection first
            var services = new ServiceCollection()
                .AddDataProtection()
                .Services
                .AddLogging(config => config.AddConsole())
                .BuildServiceProvider();

            // Call AddLogging first
            var services2 = new ServiceCollection()
                .AddLogging(config => config.AddConsole())
                .AddDataProtection()
                .Services
                .BuildServiceProvider();

            Console.WriteLine(services.GetService<ILoggerFactory>().GetType().AssemblyQualifiedName);
            Console.WriteLine(services2.GetService<ILoggerFactory>().GetType().AssemblyQualifiedName);
        }
    }
```

**output**
```
Microsoft.Extensions.Logging.Abstractions.NullLoggerFactory, Microsoft.Extensions.Logging.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Microsoft.Extensions.Logging.LoggerFactory, Microsoft.Extensions.Logging, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
```

cc @ajaybhargavb @BrennanConroy

### PR DESCRIPTION
**Pull request by natemcmaster**
Resolves #243

### CODE REVIEW

**Comment by ajaybhargavb** [comment]
cc @rynowak FYI

File: src/Microsoft.AspNetCore.DataProtection/DataProtectionServiceCollectionExtensions.cs [hunk 1]
```diff
@@ -88,10 +87,9 @@ private static void AddDataProtectionServices(IServiceCollection services)
             {
                 var dpOptions = s.GetRequiredService<IOptions<DataProtectionOptions>>();
                 var keyRingProvider = s.GetRequiredService<IKeyRingProvider>();
-                var loggerFactory = s.GetRequiredService<ILoggerFactory>();
+                var loggerFactory = s.GetService<ILoggerFactory>() ?? NullLoggerFactory.Instance;
 
-                IDataProtectionProvider dataProtectionProvider = null;
-                dataProtectionProvider = new KeyRingBasedDataProtectionProvider(keyRingProvider, loggerFactory);
+                IDataProtectionProvider dataProtectionProvider = new KeyRingBasedDataProtectionProvider(keyRingProvider, loggerFactory);
```
Comment (natemcmaster) [inline src/Microsoft.AspNetCore.DataProtection/DataProtectionServiceCollectionExtensions.cs]: Explicit typing required. Implicit typing would cause a compiler error due to the assignment that follows.
